# Action1：求2+4+6+8+...+100的求和，用Python该如何写?

In [2]:
#方法一
result=0
for i in range(2,102,2):
    result=result+i
print(result)

2550

In [3]:
print(sum([i for i in range(2,102,2)]))#方法二
print(sum(range(2,102,2))) #方法三

2550
2550

# Action2: 统计全班的成绩
班里有5名同学，现在需要你用Python来统计下这些人在语文、英语、数学中的平均成绩、最小成绩、最大成绩、方差、标准差。然后把这些人的总成绩排序，得出名次进行成绩输出（可以用numpy或pandas）

In [22]:
#Step1:建立数据表
from pandas import DataFrame
score = {'语文':[68, 95, 98, 90,80],  '数学':[65, 76, 86, 88, 90], '英语':[30, 98, 88, 77, 90]}
df= DataFrame(score, index=['张飞', '关羽', '刘备', '典韦', '许褚'], columns=['语文','数学', '英语'])
df

    语文  数学  英语
张飞  68  65  30
关羽  95  76  98
刘备  98  86  88
典韦  90  88  77
许褚  80  90  90

In [26]:
#Step2:各科的平均值、最大值他、最小值、方差、标准值
mean=df.mean()
max=df.max()
min=df.min()
std=df.std()
var=df.var()
result1=DataFrame(list(zip(mean,max,min,var,std)),index=["语文","数学","英语"],columns=["平均值","最大值","最小值","方差","标准差"])
result1

     平均值  最大值  最小值     方差        标准差
语文  86.2   98   68  150.2  12.255611
数学  81.0   90   65  109.0  10.440307
英语  76.6   98   30  734.8  27.107195

In [29]:
#Step3:求总分
sum_score=df.sum(axis=1)
sum_score

张飞    163
关羽    269
刘备    272
典韦    255
许褚    260
dtype: int64

In [31]:
#Step4:根据总分排名
sum_score.sort_values(ascending=False)

刘备    272
关羽    269
许褚    260
典韦    255
张飞    163
dtype: int64

# Action3: 对汽车质量数据进行统计

In [35]:
import pandas as pd
#Step1:数据加载
data=pd.read_csv('./car_complain.csv')

In [36]:
#df_new=df.problem.str.get_dummies(',')
#df=df.drop('problem',axis=1)#0代表没有，1代表存在
data=data.drop('problem',axis=1).join(df.problem.str.get_dummies(','))
data

,id,brand,car_model,type,desc,datetime,status,A11,A114,A12,...,N318,N319,O296,O326,O348,O354,Q322,Q323,Q349,Q350
0,482028,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹B柱异响 车内异响严重,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,482027,江淮汽车,江淮iEV6E,2017款 iEV6E,江淮iEV6E动力电池故障 无法充电,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,482026,一汽马自达,阿特兹,2020款 2.5L 蓝天运动版,一汽马自达阿特兹车身异响 天窗异响,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,482022,一汽-大众,迈腾,2009款 1.8TSI DSG 舒适型,一汽大众迈腾起步和刹车时车辆抖动\t,2020-06-08,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,482019,众泰汽车,众泰T600 Coupe,2017款 1.5T 自动 尊享型,众泰T600 Coupe售后维修配件一直缺货,2020-06-08,厂家受理,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,480802,北京现代,领动,2016款 1.6L 自动 智炫·精英型,北京现代领动ABS和防侧滑故障灯同时亮\t,2020-06-05,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
596,480801,一汽-大众,高尔夫,2016款 1.4TSI 25周年纪念版,一汽大众高尔夫仪表提示变速箱挂入P挡,2020-06-05,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0
597,480799,吉利汽车,星越,2020款 350T 魅影骑士版AWD,吉利星越车机系统虚假宣传 卡顿严重,2020-06-05,用户评分,0,0,0,...,0,0,0,0,0,0,0,0,0,0
598,480798,北京现代,悦纳,2016款 1.4L 手动 炫酷版 GLS,北京现代悦纳发动机曲轴螺丝断裂,2020-06-05,信息审核,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,480795,东风日产,逍客,2016款 2.0L CVT 精英版,东风日产逍客变速箱报故障码P17F1,2020-06-05,处理反馈,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
#Step2:清洗数据
def f(x):
    x=x.replace('一汽-大众','一汽大众')
    return (x)
data['brand']=data['brand'].apply(f)

In [53]:
#A31;品牌投诉总数排序
result=data.groupby(['brand'])['id'].agg(['count'])
result.sort_values('count',ascending=False)

        count
brand
吉利汽车       96
一汽马自达      95
一汽大众       58
上汽大众       36
一汽大众奥迪     19
...       ...
天津一汽        1
多士星         1
北汽新能源       1
北汽昌河        1
东风小康        1

[74 rows x 1 columns]

In [54]:
#A32:车型投诉总数排序
result2=data.groupby(['car_model'])['id'].agg(['count'])
result2.sort_values('count',ascending=False)

           count
car_model
阿特兹           75
星越            43
速腾            22
马自达CX-4       20
博越            13
...          ...
悦翔             1
捷豹XEL          1
捷豹XFL          1
撼路者            1
高尔夫（进口）        1

[212 rows x 1 columns]

In [78]:
#A33:哪个品牌的平均车型投诉最多
import numpy as np
result3=data.groupby(['brand','car_model'])['id'].agg(['count'])
#print(result3)
#01求品牌投诉总数
brand_complain_count=result3.groupby(['brand'])['count'].agg(['sum'])
#02求品牌对应的车型数
result5=result3.groupby(['brand','car_model']).agg(['count'])
brand_model_count=result5.groupby(['brand'])['count'].agg(['sum'])
#print(result4)
#print(result5)
#03求品牌的平均车型投诉数
avg_complain=DataFrame(np.divide(brand_complain_count,brand_model_count))
#04对品牌的平均车型投诉数排序
avg_complain=avg_complain.sort_values('sum',ascending=False)
avg_complain.rename(columns={'sum': 'average car complain'}, inplace = True)
avg_complain

        avg car complain
brand
一汽马自达          47.500000
吉利汽车            9.600000
一汽大众            8.285714
广汽丰田            5.666667
上汽大众            3.600000
...                  ...
东风乘用车           1.000000
奔驰（进口）          1.000000
奥迪（进口）          1.000000
宝沃汽车            1.000000
一汽解放            1.000000

[74 rows x 1 columns]